# Generated by Django 4.0.6 on 2023-06-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teste',
            new_name='Product',
        ),
    ]
