# Generated by Django 4.0.6 on 2023-06-06 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('doc', models.CharField(default='', max_length=14)),
                ('doc_type', models.CharField(choices=[('CNPJ', 'CNPJ'), ('CPF', 'CPF')], default='', max_length=4)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
